import type { Metadata } from 'next'
import AppSidebar from './AppSidebar'
import AppHeader from './AppHeader'
import ProtectedRoute from './ProtectedRoute'

export const metadata: Metadata = {
    title: 'App',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ProtectedRoute>
            <div className='flex'>
                <AppSidebar />

                <div className='flex-1 ml-60'>
                    <AppHeader />
                    <div className='pb-60'>
                        {children}
                    </div>
                </div>
            </div>
        </ProtectedRoute>
    )
}
